version: "3"

services:

  api:
    # build:
    #   context: .
    #   dockerfile: docker/Dockerfile
    image: ye2531/spam-images-detector:latest
    ports:
      - "8000:8000"
    volumes:
      - "./:/app"